# page rank

In [4]:
import numpy as np
a = np.array ([[0.25], [0.25], [0.25], [0.25]])
b = np.array ([[0.37], [0.08], [0.33], [0.20]])

print (a*b)

[[0.0925]
 [0.02  ]
 [0.0825]
 [0.05  ]]


In [6]:
import numpy as np
A = np.array ([[0,0,1,1/2],[1/3,0,0,0],[1/3,1/2,0,1/2],[1/3,1/2,0,0]])
V0 = np.array ([[0.25],[0.25],[0.25],[0.25]])
V1 = A@V0
print(V1)
V2 = A@V1
print(V2)
V3 = A@V2
print(V3)
V4 = A@V3
print(V4)
V5 = A@V4
print(V5)
V6 = A@V5
print(V6)
V7 = A@V6
print(V7)
V8 = A@V7
print(V8)
V0 = np.array ([[0.3],[0.2],[0.3],[0.2]])
V1 = A@V0
print(V1)
V2 = A@V1
print(V2)
V3 = A@V2
print(V3)
V4 = A@V3
print(V4)
V5 = A@V4
print(V5)
V6 = A@V5
print(V6)
V7 = A@V6
print(V7)
V8 = A@V7
print(V8)

[[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
[[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
[[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
[[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
[[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
[[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
[[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]
[[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]
[[0.4]
 [0.1]
 [0.3]
 [0.2]]
[[0.4       ]
 [0.13333333]
 [0.28333333]
 [0.18333333]]
[[0.375     ]
 [0.13333333]
 [0.29166667]
 [0.2       ]]
[[0.39166667]
 [0.125     ]
 [0.29166667]
 [0.19166667]]
[[0.3875    ]
 [0.13055556]
 [0.28888889]
 [0.19305556]]
[[0.38541667]
 [0.12916667]
 [0.29097222]
 [0.19444444]]
[[0.38819444]
 [0.12847222]
 [0.29027778]
 [0.19305556]]
[[0.38680556]
 [0.12939815]
 [0.29016204]
 [0.19363426]]
