# Determinant Matrix
Membuat matrix identitas dengan code fungsi python untuk membuktikan determinan matrix identitas (sifat-sifat determinan).

Sifat-sifat Matrix determinan:

1. Jika baris Matrix Identitas ditukar maka akan mengubah tanda dari Determinan Matrix Identitas tersebut

2. Jika di dalam suatu Matrix ada baris atau yang merupakan kelipatan dari baris atau kolom yang lain maka det = 0.

3. Jika ada Matrix kelipatan dari matrix lain maka determinan matrix tersebut adalah kelipatan pangkat ordo kali determinan matrix dari kelipatannya.

4. Jika Determinan Matrix B adalah 2x Determinan Matrix A maka ada salah satu baris Matrix B yang menjadi 2x lipat baris Matrix A.

5. Jika ada matrix yang berasal dari penjumlahan matrix A dan matrix B maka determinannya adalah penjumlahan dari matrix A dan Matrix B.

6. Jika ada Matrix segitiga atas maka determinannya adalah perkalian anggota diagonal Matrix tersebut.

In [5]:
import numpy as np

A = np.array([[1,0],[0,1]])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
C = np.array([[1,0,0],[0,0,1],[0,1,0]])
D = np.array([[0,1,0],[0,0,1],[1,0,0]])
E = np.array([[1,2,1],[3,1,2],[2,1,2]])
F = np.array([[3,1,2],[1,2,1],[2,1,2]])
G = np.array([[1,2,1],[2,4,2],[2,1,2]])
H = np.array([[1,2,2],[2,4,4],[1,2,3]])
I = np.array([[6,2,4],[2,4,2],[4,2,4]])
J = np.array([[3,4],[2,1]])
K = np.array([[6,8],[4,2]])
L = np.array([[2*3,2*4],[2,1]])
M = np.array([[2*3,4],[2*2,1]])
N = np.array([[4,1],[2,1]])
O = np.array([[7,5],[2,1]])
P = np.array([[2,3,2],[0,2,2],[0,0,2]])
Q = np.array([[2,1],[1,1]])
R = np.array([[1,1],[1,1]])
S = np.array([[3,3],[2,2]])


det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_F = np.linalg.det(F)
det_G = np.linalg.det(G)
det_H = np.linalg.det(H)
det_I = np.linalg.det(I)
det_J = np.linalg.det(J)
det_K = np.linalg.det(K)
det_L = np.linalg.det(L)
det_M = np.linalg.det(M)
det_N = np.linalg.det(N)
det_O = np.linalg.det(O)
det_P = np.linalg.det(P)
det_Q = np.linalg.det(Q)
det_R = np.linalg.det(R)
det_S = np.linalg.det(S)


print(f"Determinant dari matriks A =\n{A} adalah {det_A}\n")
print(f"Determinant dari matriks B =\n{B} adalah {det_B}\n")
print(f"Determinant dari matriks C =\n{C} adalah {det_C}\n")
print(f"Determinant dari matriks D =\n{D} adalah {det_D}\n")
print(f"Determinant dari matriks E =\n{E} adalah {det_E}\n")
print(f"Determinant dari matriks F =\n{F} adalah {det_F}\n")
print(f"Determinant dari matriks G =\n{G} adalah {det_G}\n")
print(f"Determinant dari matriks H =\n{H} adalah {det_H}\n")
print(f"Determinant dari matriks I =\n{I} adalah {det_I}\n")
print(f"Determinant dari matriks J =\n{J} adalah {det_J}\n")
print(f"Determinant dari matriks K =\n{K} adalah {det_K}\n")
print(f"Determinant dari matriks L =\n{L} adalah {det_L}\n")
print(f"Determinant dari matriks M =\n{M} adalah {det_M}\n")
print(f"Determinant dari matriks N =\n{N} adalah {det_N}\n")
print(f"Determinant dari matriks O =\n{O} adalah {det_O}\n")
print(f"Determinant dari matriks P =\n{P} adalah {det_P}\n")
print(f"Determinant dari matriks Q =\n{Q} adalah {det_Q}\n")
print(f"Determinant dari matriks R =\n{R} adalah {det_R}\n")
print(f"Determinant dari matriks S =\n{S} adalah {det_S}\n")



Determinant dari matriks A =
[[1 0]
 [0 1]] adalah 1.0

Determinant dari matriks B =
[[1 0 0]
 [0 1 0]
 [0 0 1]] adalah 1.0

Determinant dari matriks C =
[[1 0 0]
 [0 0 1]
 [0 1 0]] adalah -1.0

Determinant dari matriks D =
[[0 1 0]
 [0 0 1]
 [1 0 0]] adalah 1.0

Determinant dari matriks E =
[[1 2 1]
 [3 1 2]
 [2 1 2]] adalah -3.000000000000001

Determinant dari matriks F =
[[3 1 2]
 [1 2 1]
 [2 1 2]] adalah 3.000000000000001

Determinant dari matriks G =
[[1 2 1]
 [2 4 2]
 [2 1 2]] adalah 0.0

Determinant dari matriks H =
[[1 2 2]
 [2 4 4]
 [1 2 3]] adalah 0.0

Determinant dari matriks I =
[[6 2 4]
 [2 4 2]
 [4 2 4]] adalah 24.000000000000014

Determinant dari matriks J =
[[3 4]
 [2 1]] adalah -5.000000000000001

Determinant dari matriks K =
[[6 8]
 [4 2]] adalah -19.999999999999996

Determinant dari matriks L =
[[6 8]
 [2 1]] adalah -9.999999999999998

Determinant dari matriks M =
[[6 4]
 [4 1]] adalah -9.999999999999998

Determinant dari matriks N =
[[4 1]
 [2 1]] adalah 2.0

Determ